module.exports = {
  accountVerify: require("./accountVerify"),
  passwordReset: require("./passwordReset"),
  welcome: require("./welcome"),
  userContact: require("./userContact"),
  passwordChanged: require("./passwordChanged"),
  newSubscription: require("./newSubscription"),
  submissionApproved: require("./submissionApproved"),
  submissionDeclined: require("./submissionDeclined"),
  subscriptionActivated: require("./subscriptionActivated"),
  newSubmission: require("./newSubmission"),
  roleChanged: require("./roleChanged"),
  submissionDeleted: require("./submissionDeleted"),
  linksAdded: require("./linksAdded"),
  accountTypeChanged: require("./accountTypeChanged"),
};
